/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponentA {
    }
}
declare global {
    interface HTMLMyComponentAElement extends Components.MyComponentA, HTMLStencilElement {
    }
    var HTMLMyComponentAElement: {
        prototype: HTMLMyComponentAElement;
        new (): HTMLMyComponentAElement;
    };
    interface HTMLElementTagNameMap {
        "my-component-a": HTMLMyComponentAElement;
    }
}
declare namespace LocalJSX {
    interface MyComponentA {
    }
    interface IntrinsicElements {
        "my-component-a": MyComponentA;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component-a": LocalJSX.MyComponentA & JSXBase.HTMLAttributes<HTMLMyComponentAElement>;
        }
    }
}
